name: Reusable NPM Script Run

on:
  workflow_call:
    inputs:
      script_name: 
        required: true
        type: string
      node_version:
        default: 'lts/*'
        required: false
        type: string

jobs:
  npm_script_run:
    runs-on: ubuntu-latest
    steps: 
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with: 
          version: 6.14.7

      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ inputs.node_version }}
          cache: 'pnpm'
        
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm ${{ inputs.script_name }}
