name: Reusable NPM Script Run

on:
  workflow_call:
    inputs:
      script_name: 
        required: true
        type: string

jobs:
  npm_script_run:
    runs-on: ubuntu-latest
    steps: 
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Cache pnpm Modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup Node
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.7
          run_install: true

      - run: pnpm ${{ inputs.script_name }}
